// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUgP94BDGM3NFGUIF0xXJYq-AotP33trs',
    appId: '1:35537530933:web:a83d3a566658482615817c',
    messagingSenderId: '35537530933',
    projectId: 'my-hostel-89819',
    authDomain: 'my-hostel-89819.firebaseapp.com',
    storageBucket: 'my-hostel-89819.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX2cmOyM5j-mkEmWEexX7bvPiaipjUxQo',
    appId: '1:35537530933:android:35f0395deed17cbc15817c',
    messagingSenderId: '35537530933',
    projectId: 'my-hostel-89819',
    storageBucket: 'my-hostel-89819.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiroWziXoHgegdIq-pcj_2Fr-wAM0niPk',
    appId: '1:35537530933:ios:85fdc46d1d2f7d2515817c',
    messagingSenderId: '35537530933',
    projectId: 'my-hostel-89819',
    storageBucket: 'my-hostel-89819.firebasestorage.app',
    iosBundleId: 'com.example.myHostelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiroWziXoHgegdIq-pcj_2Fr-wAM0niPk',
    appId: '1:35537530933:ios:85fdc46d1d2f7d2515817c',
    messagingSenderId: '35537530933',
    projectId: 'my-hostel-89819',
    storageBucket: 'my-hostel-89819.firebasestorage.app',
    iosBundleId: 'com.example.myHostelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUgP94BDGM3NFGUIF0xXJYq-AotP33trs',
    appId: '1:35537530933:web:68795de7a0d987e215817c',
    messagingSenderId: '35537530933',
    projectId: 'my-hostel-89819',
    authDomain: 'my-hostel-89819.firebaseapp.com',
    storageBucket: 'my-hostel-89819.firebasestorage.app',
  );
}
